theme: jekyll-theme-minimal
title: Serena A. Cronin
description: I am a recent graduate (Dec. 2020) of The Ohio State University with a BSc in Astronomy and Astrophysics and a minor in Spanish. I am a student researcher at OSU and a (virtual) post-bacc intern at the National Radio Astronomy Observatory (NRAO) of Socorro, New Mexico. In the summer of 2020, I was a (virtual) NSF REU student at NRAO. 
logo: 96564DE9-3767-4D7F-978A-A190C130481A_1_105_c.jpeg
