theme: jekyll-theme-minimal
title: Serena Cronin
description: I am a senior undergraduate student at The Ohio State University. I am studying Astronomy and Astrophysics with a minor in Spanish. I have been involved in research since 2018 and teaching since 2017. My expected graduation is Fall 2020!
link: [Twitter] www.twitter.come/serspace
