theme: jekyll-theme-minimal
title: Serena A. Cronin
description: I am a senior undergraduate student at The Ohio State University studying Astronomy and Astrophysics with a minor in Spanish. I am a student research assistant at OSU and an NSF REU student at the National Radio Astronomy Observatory (NRAO) in Socorro, New Mexico.
logo: serc7.github.io/96564DE9-3767-4D7F-978A-A190C130481A_1_105_c.jpeg
